name: Pankaj Kataria
description: Pankaj Kataria on software security, technology and stuff
url: https://pankajkataria.github.io/
markdown: kramdown
include: ['.htaccess']
highlighter: pygments
comments: true

paginate: 5
paginate_path: "/blog/page:num"
permalink: "/blog/:title/"

gems: [jekyll-paginate]
